server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否将自己注册到Eureka Server，默认为true，为Server端时设置为false
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认为true，为Server端时设置为false
    fetchRegistry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: mycloud-eureka-server
