spring:
  application:
    name: mycloud-eureka-server-9000

server:
  port: 9000

eureka:
  instance:
    hostname: eureka01.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka02.com:9001/eureka/,http://eureka03.com:9002/eureka/



