spring:
  application:
    name: mycloud-eureka-server-9001

server:
  port: 9001

eureka:
  instance:
    hostname: eureka02.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka01.com:9000/eureka/,http://eureka03.com:9002/eureka/



